version: "3.8"

services:
    clickhouse:
        image: clickhouse/clickhouse-server:24.8-alpine
        container_name: click-house
        ports:
            - "9000:9000"
            - "8123:8123"
        environment:
            CLICKHOUSE_DB: logs_db
            CLICKHOUSE_USER: default
            CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
        volumes:
            - ch_data:/var/lib/clickhouse
            - ./init-ch.sql:/docker-entrypoint-initdb.d/init.sql
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
volumes:
    ch_data:
            
